:PROPERTIES:
:ID:       0b8d3fe0-0bc7-4845-8028-7a2042137b4b
:END:
#+title: cc-tool
#+STARTUP: overview
#+date: 2024-09-11
#+filetags: apps

Para la instalación de cc-tool en Linux Mint hay que instalar las dependencias, clonar el repositorio y compilarlo para nuestra máquina. Arrancamos con los siguientes comandos:
#+begin_src bash
  sudo apt-get update
  sudo apt-get install git build-essential libusb-1.0-0-dev
  sudo apt-get install automake autoconf libtool
  git clone https://github.com/dashesy/cc-tool.git
  cd cc-tool
#+end_src

El siguiente paso es configurar la compilación
#+begin_src bash
./configure
#+end_src

Durante el configure obtengo un error que indica que no dispongo de la versión de Boost igual o superior a 1.74:
#+begin_src bash
configure: error: cannot find Boost headers version >= 1.74.0
#+end_src

Instalamos la versión requerida de Boost: (1.74)

Mediante apt se instala la versión 1.71 por lo que hay que descargarla de la web y compilarla para nuestra máquina mediante las siguientes instrucciones.
#+begin_src 
wget https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.tar.gz
tar -xzf boost_1_74_0.tar.gz
cd boost_1_74_0
./bootstrap.sh
sudo ./b2 install
#+end_src

Con Boost ya instalado, intento de nuevo la configuración de la compilación
#+begin_src bash
./configure
#+end_src

Ahora, al hacer el "Configure" obtengo el error:
#+begin_src bash
configure: error: the libext variable is empty, did you invoke Libtool?
#+end_src

Parece que no tengo instalado "Libtool" o instalado incorrectamente por lo que lo reinstalo.
#+begin_src bash
sudo apt-get install --reinstall libtool
#+end_src

Volvemos a regenerar el archivo configure:
#+begin_src bash
./configure
#+end_src

Al fin lo pasa sin error pero ahora al hacer el "make" obtengo este error:
#+begin_src bash
configure.ac:8: error: required file './compile' not found
#+end_src

Para corregir este error hay que regenerar los archivos de Autotools y realizar la compilación:
#+begin_src bash
autoreconf --install
make
sudo make install
cc-tool --version
#+end_src

Al comprobar la versión instalada de cc-tool obtengo este error:
#+begin_src bash
cc-tool: error while loading shared libraries: libboost_filesystem.so.1.74.0: cannot open shared object file: No such file or directory
#+end_src

Para corregirlo hay que actualizar las rutas de bibliotecas compartidas:
#+begin_quote
El comando ldconfig se usa para actualizar la caché de las bibliotecas dinámicas del sistema, lo cual es necesario si has instalado bibliotecas manualmente o si has agregado nuevas rutas de búsqueda de bibliotecas. Esta solución debería permitir que cc-tool encuentre la biblioteca libboost_filesystem.so.1.74.0 y se ejecute correctamente.
#+end_quote

Al instalar manualmente Boost hay que agregar el directorio de las bibliotecas de Boost (generalmente /usr/local/lib si instalaste desde la fuente) a las rutas de búsqueda y actualizar la actualiza la caché de las bibliotecas dinámicas:
#+begin_src bash
echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/boost.conf
sudo ldconfig
#+end_src

Con sólo estos pasos podemos decir que ya tenemos instalado cc-tool.



