:PROPERTIES:
:ID:       f101a6aa-063a-4e6c-9f11-ef68717cb524
:END:
#+title: Homepage Docker
#+STARTUP: overview
#+date: 2026-01-04
** Info
Homepage es un panel de inicio y dashboard altamente personalizable para tu infraestructura y servicios auto-alojados. Es una aplicación web rápida, segura y totalmente estática, configurable mediante archivos YAML o etiquetas Docker, y con soporte para más de 100 integraciones de servicios y widgets como tiempo, reloj y estado de contenedores. Permite agrupar enlaces y servicios en un solo lugar, mostrar estado y métricas, y extenderse con widgets personalizados. Su integración con Docker y Kubernetes facilita la detección automática de servicios y su monitorización. Está diseñado para ser usado detrás de un proxy seguro o VPN.
** Uso
Mi página de inicio de servicios autoalojados

** Enlace
https://gethomepage.dev
http://homepage.zgz.sherblog.es

** Variables de entorno
-  HOMEPAGE_ALLOWED_HOSTS: Separados por comas los host en los que está corriendo

** docker-compose.yml
#+begin_src yaml
services:
  homepage:
    user: "1000:1000"
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 4000:3000
    volumes:
      - /home/sherlockes/dockers/homepage/data:/app/config
      - /home/sherlockes/dockers/homepage/data/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.zgz.sherblog.es,192.168.10.211:4000
networks: {}
#+end_src

** Gestión
#+begin_src bash
  docker compose up -d
  docker compose logs -f 
  docker compose restart 
#+end_src

** Notas
- Favoritos: bookmarks.yaml
- Servicios: services.yaml

